### ISSUE TITLE
Question about Yggrasil Authentication Service

### ISSUE THREAD

**Issue by DefinitlyEvil** [Mojang/stats.minecraft.net#1]
Hello,
I am doing DragonProxy project which uses this service. 
My friend said `Mojang will rate block you after a lot of authentications from different accounts, it takes 2-3 hours to remove the IP block.`, is this true? 
Thanks for reading. ;)

**Comment by egold555** [comment]
Yes this is true.

**Comment by DefinitlyEvil** [comment]
@egold555 No longer deal with this but thx anyways. 😝
